### ISSUE TITLE
NameError: name 'KEY' is not defined

### ISSUE THREAD

**Issue by Pepepy** [Quantika14/email-prediction-asterisks#4]
Hola,
Al ejecutar me lanza el siguiente error
Traceback (most recent call last):
  File "/home/kali/PROGRAMAS/email-prediction-asterisks/app.py", line 4, in <module>
    import m.utils as utils
  File "/home/kali/PROGRAMAS/email-prediction-asterisks/m/utils.py", line 60
    if KEY.intelx == "";
                       ^
SyntaxError: invalid syntax

Si modifico los ; por : para que sea correcta la sintaxis me lanza este:

Traceback (most recent call last):
  File "/home/kali/PROGRAMAS/email-prediction-asterisks/app.py", line 222, in <module>
    utils.check_APIS_KEY()
  File "/home/kali/PROGRAMAS/email-prediction-asterisks/m/utils.py", line 59, in check_APIS_KEY
    if KEY.intelx == "":
NameError: name 'KEY' is not defined

supongo que es porque no esta importado el modulo key, pero no me deja importarlo tampoco. Alguna idea de porque puede ser?

**Comment by Quantika14** [comment]
Falta importar en UTILS el modulo KEY.
Ya está.
